### ISSUE TITLE
upload_template seemingly ignores use_sudo, chown, etc.

### ISSUE THREAD

**Issue by chrzyki** [shh-dlce/appconfig#10]
After using `upload_template` from either `fabric` itself or `fabric.contrib`, the uploaded templates always (as far as I can tell) belong to the uploading user's (SSH) account. I **think** the files are uploaded to the user's home directory and then `sudo mv`ed to their target location, keeping the original modes.

This has already happened for a couple of our files and needs to be fixed, at least for stuff in `/etc`.

**Comment by chrzyki** [comment]
Can be 'fixed' by providing a `user` argument, that is then used in the subsequent sftp `put` operations. I.e. if you specify `user='root'`, you get the proper permissions.

**Comment by xflr6** [comment]
https://github.com/shh-dlce/appconfig/blob/7b5a0bb278291074c9ab08f05c8e43ee4d7a7617/appconfig/tasks/deployment.py#L77
AFAIR, we need `use_jinja`: some templates use logic, e.g. `config.ini`.
https://github.com/shh-dlce/appconfig/blob/7b5a0bb278291074c9ab08f05c8e43ee4d7a7617/appconfig/tasks/deployment.py#L61
Shouldn't this be `user_own='root'`?

**Comment by chrzyki** [comment]
`user_jinja=False` was a mistake, will fix.

Didn't set `user_own` to anything in particular in order to give access to the potentially wanted behaviour of having other user permissions.

**Comment by xflr6** [comment]
Allright, thanks (I thought the bug was that we would expect/want all files to be owned by root when using the little `sudo_upload_template` wrapper here).

**Comment by chrzyki** [comment]
And thank you for noticing the `use_jinja`. Played around with this and simply forget to change it back. Duh. :)
