### ISSUE TITLE
Rolling db backups to cdstar

### ISSUE THREAD

**Issue by xrotwang** [shh-dlce/appconfig#25]
To go ahead with the idea of "disposable servers", even when faced with write-able databases like cobl or soundcomparisons, we need a DB-backup task - pretty much logrotate for DB dumps, writing to cdstar.

Ideally, this task would use a local JSON catalog (possibly via `cdstarcat`) to also make is possible to retrieve the latest dump programmatically for deployments.

Implementation already started:
- DB dumps on CDSTAR are done using the RollingBlob functionality,
- with a fixed CDSTAR OID, which is added as attribute to the apps appconfig.

The task then should create and upload a new dump and stop (un-deploy even?) the app.

The corresponding deploy task should then retrieve the DB dump from CDSTAR.

**Comment by xrotwang** [comment]
Could be implemented by using 
- **one** fixed cdstar object for the backups of a given app, and
- adding a bitstream per backup (using the data as bitstream name)

with an additional cleanup command, keeping only the n youngest bitstreams for each object registered as "backup object".

**Comment by chrzyki** [comment]
> (Needs checking: Can individual bitstreams be deleted?)
```python
bs = obj.bitstreams.pop()
bs.delete()
```
Or am I misunderstanding something?

**Comment by xrotwang** [comment]
Yes, I'd hope this works.

**Comment by chrzyki** [comment]
Works. Tested & verified. :)

**Comment by chrzyki** [comment]
Only thing is that the response code is 204 which, at least to me, was unexpected but makes sense in the context I guess.

**Comment by xrotwang** [comment]
Maybe `ISO-DATE.sql.gz` would be suitable names?

**Comment by xrotwang** [comment]
Dunno if there's a suitable mimetype for gzipped sql.

**Comment by chrzyki** [comment]
Am big fan of time stamps in ISO date (i.e. `20180626T082548Z`). Mimetype: `application/gzip` according to [RFC 6713](https://tools.ietf.org/html/rfc6713)?

**Comment by xrotwang** [comment]
yes. good. Maybe we should make this generic enough to also cover stuff like the map tiles for soundcomparisons' offline version. So it will not strictly be backups, but blobs of which only most recent versions are needed.

**Comment by xrotwang** [comment]
Some support for this is now in [cdstarcat](https://github.com/clld/cdstarcat/commit/7f7412880f596b614d8a807fa7bf5e24e3ac9928)

**Comment by chrzyki** [comment]
👍 for rolling blobs.

**Comment by xrotwang** [comment]
They actually work quite well. I created one for cobl and now you can add to it with relatively simple code like
```python
import os

from cdstarcat import Catalog


def main():
    env = os.environ
    with Catalog(
        env['CDSTAR_CATALOG'],
        cdstar_url=env['CDSTAR_URL'],
        cdstar_user=env['CDSTAR_USER'],
        cdstar_pwd=env['CDSTAR_PWD'],
    ) as cat:
        cat.add_rollingblob('2018-06-27.sql.bz2', oid='EAEA0-0A0A-F2DF-237F-0', suffix='.sql.bz2', keep=1)


if __name__ == '__main__':
    main()
```

**Comment by chrzyki** [comment]
Pretty awesome! Surprised and impressed with how little code you've made a pretty neat and stable backup solution. I can see this being useful for more than just our DB backup questions.

**Comment by chrzyki** [comment]
`keep` adds to the object and if more than `keep` bitstreams are in the object the oldest is deleted?

**Comment by xrotwang** [comment]
yes, only the `keep` most recent bitstreams are kept. This is not the "independent cleanup task" idea I had first. But it makes sense, I think, in particular in a scenario, where backups are not uploaded automatically, but triggered as a pre-requisite for a subsequent deployment. In this case, only "known good" backups are uploaded and the issue of automatically piling up corrupt backups until all good ones are expunged is avoided.

**Comment by xrotwang** [comment]
This is supported now, see https://github.com/shh-dlce/appconfig/blob/be91ac796228481a5497e19f0d878934af2a1032/appconfig/tasks/other.py#L43
