### ISSUE TITLE
soundcomparisons - avoid publishing links to wav sound files in web site

### ISSUE THREAD

**Issue by Bibiko** [shh-dlce/appconfig#32]
https://github.com/shh-dlce/appconfig/blob/95396dd30b37747863a5be50e76321c8badd1f64/apps/soundcomparisons/fabfile.py#L112-L116

Due to the fact that the underlying JavaScript App tries to preload listed sound files of a web page in the background no wav sound files should be published within a web page. Furthermore wav sound files are for advanced users only and these users should ask the author(s) for them.

**Comment by Bibiko** [comment]
one possible solution would be in line 116:

`oid, stem, fmt) for fmt in list(set(fmts) & set(['mp3','ogg'])]`

**Comment by xrotwang** [comment]
Please go ahead and change as appropriate. This task was mainly intended to
get us started, I'd appreciate you taking over from here.

Hans-Jörg Bibiko <notifications@github.com> schrieb am Mi., 8. Aug. 2018,
18:06:
