### ISSUE TITLE
Task to remove an app from a server

### ISSUE THREAD

**Issue by xrotwang** [shh-dlce/appconfig#7]
We need a task to undo the deployment of an app, i.e.
- remove the supervisord config
- remove the nginx config
- remove the virtualenv
- drop the database
- remove the user and home dir
- restart supervisord and nginx

**Comment by chrzyki** [comment]
Done in 96302be909ad6c89321637f864c99aa995b882e7.

**Comment by xrotwang** [comment]
@chrzyki maybe one should test for existence of the database as well before dropping? Don't know from the top of my head how to do this quickly, though. Maybe fabtools has something for this?

**Comment by xflr6** [comment]
https://www.postgresql.org/docs/9.3/static/app-dropdb.html

> --if-exists
> Do not throw an error if the database does not exist. A notice is issued in this case.

**Comment by xrotwang** [comment]
yep, that would do.

**Comment by chrzyki** [comment]
So use `--if-exists` and drop the db as `postgres` & skip the user-check?

**Comment by xflr6** [comment]
Hm, we can still leave the user check in to make the app removal idemotent (not fail if it is run again).

**Comment by xrotwang** [comment]
yes, keep user check - or reduce to just one user check by combining with the userdel.
