### ISSUE TITLE
"Deploy with py2.7" config setting

### ISSUE THREAD

**Issue by xrotwang** [shh-dlce/appconfig#8]
We may need a "deploy with py2.7" config setting, in case porting an app would  take too much time. The app have in mind is `grambank`, largely maintained by @d97hah, who's still on py2 only :)

**Comment by d97hah** [comment]
Yes still on 2.7

2018-01-13 21:37 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
Looks like we'll be able to make grambank run on py3.
